config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "static_pages/home"
  match "/home" => redirect("/"), via: [:get]
  match "/privacy" => "static_pages#privacy", via: [:get]
  match "/terms_of_service" => "static_pages#terms_of_service", via: [:get]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    match "/profile" => "users/registrations#edit", via: [:get]
    get "/users/sign_out" => "users/sessions#destroy"
  end

  # The User-Facing application. People who have registered for an account go here.
  resources :achievements
  resources :billing_methods
  resource :dashboard, controller: "dashboard"
  resources :registrations, only: [:index, :show]

  # The Admin Facing Application. Admin users will be directed here.
  authenticate :user, lambda { |u| u.is_admin? } do
    namespace :admin do
      resource :dashboard, controller: "dashboard"
      resources :series
      resources :users
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
  belongs_to :user
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :series
  has_many :registrations
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :race
end

app/models/series.rb
class Series < ApplicationRecord
  validates :name, presence: true
  validates :short_description, presence: true
  validates :long_description, presence: true

  has_one_attached :promo_image
  has_one_attached :banner_image
  has_many_attached :gallery_image
end

app/models/user.rb
class User < ApplicationRecord
  default_scope -> { where(deleted_at: nil) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :registrations
  has_one_attached :avatar


  DIVISIONS = ["FEMALE", "MALE", "OPEN"].freeze

  def soft_delete!
    update(:deleted_at, Time.current)
  end

  def level
    ["Newcomer", "Learner", "Master", "Veteran", "Elite"].sample
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout -> (controller) { controller.request.xhr? ? false : 'admin' }
  before_action :require_admin!, :set_body_class

  protected

  def set_body_class
    @body_class = "show-sidebar"
  end

  def require_admin!
    unless current_user.present? && current_user.is_admin?
      flash[:alert] = "This is for admin users only. Move along!"
      redirect_to root_path
    end
  end
  helper_method :require_admin!
end

app/controllers/admin/series_controller.rb
class Admin::SeriesController < Admin::BaseController
  layout "admin"

  before_action :set_series, only: [:show, :edit, :update, :destroy]

  def index
    @series = Series.all
  end

  def show
  end

  def new
    @series = Series.new
  end

  def edit
  end

  def create
    @series = Series.new(series_params)

    if @series.save
      redirect_to(
        admin_series_path(@series),
        notice: "Series was successfully created."
      )
    else
      render :new
    end
  end

  def update
    if @series.update(series_params)
      redirect_to(
        admin_series_path(@series),
        notice: "Series was successfully updated."
      )
    else
      render :edit
    end
  end

  def destroy
    @series.destroy
    redirect_to(
      admin_series_index_path,
      notice: "Series was successfully destroyed."
    )
  end

  private

  def set_series
    @series = Series.find(params[:id])
  end

  def series_params
    params.require(:series).permit(
      :name,
      :short_description,
      :full_description,
      :allows_mass_registration,
      :mass_registration_open_at,
      :contact_email,
      :contact_name
    )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"

  def index
    @user = User.all
  end

  def edit

  end

  def update
  end

  def destroy
  end

  private

  def find_user
    @user = User.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    edit_user_registration_path # User Profile View
  end

  protected
  
  def current_user
    super&.decorate
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!

end

app/controllers/registrations_controller.rb
class RegistrationsController < BaseController
  layout "application"

  def index
    @registrations = current_user.registrations
  end

  def show
    @registration = current_user.registrations.find(params[:id])
    @race = @registration.race
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "landing"

  def home
  end

  def privacy
  end

  def terms_of_service
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :set_sanitized_params, only: :create
  before_action :update_sanitized_params, only: :update

  layout :resolve_layout

  # PUT /resource/invitation
  def update
    respond_to do |format|
      format.js do
        invitation_token = Devise.token_generator.digest(
          resource_class,
          :invitation_token,
          update_resource_params[:invitation_token]
        )
        self.resource = resource_class.where(
          invitation_token: invitation_token
        ).first
        resource.skip_password = true
        resource.update_attributes update_resource_params.except(
          :invitation_token
        )
      end
      format.html do
        super
      end
    end
  end

  protected

  def set_sanitized_params
    devise_parameter_sanitizer.permit(
      :invite,
      keys: [
        :email,
        :full_name,
        :preferred_name,
        :mobile_phone
      ]
    )
  end

  def update_sanitized_params
    devise_parameter_sanitizer.permit(
      :accept_invitation,
      keys: [
        :full_name,
        :preferred_name,
        :email
        :password,
        :password_confirmation,
        :invitation_token,
        :cell_phone
      ]
    )
  end

  def after_invite_path_for(resource)
    if current_inviter.is_admin?
      flash[:notice] = 'Invitation Sent'
      redirect_to admin_dashboard_path
    else
      after_sign_in_path_for(current_inviter)
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  layout :resolve_layout

  def destroy
    resource.soft_delete!
    super
  end

  protected

  def configure_permitted_parameters
    the_keys = [
      :allows_email,
      :allows_texting,
      :avatar,
      :birthdate,
      :cell_phone,
      :full_name,
      :hometown,
      :is_rogue_member,
      :life_long_athlete,
      :medical_notes,
      :preferred_division,
      :preferred_name,
      :preferred_shirt_size,
      :time_zone
    ]
    devise_parameter_sanitizer.permit(:sign_up, keys: the_keys)
    devise_parameter_sanitizer.permit(:account_update, keys: the_keys)
  end

  def after_sign_up_path_for(resource)
    # will be user_signups_path
  end

  def after_update_path_for(resource)
    edit_user_registration_path
  end

  def resolve_layout
    case action_name
    when "new", "create"
      "devise"
    else
      "application"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    "Spectrum Trail Running"
  end

  def current_user?
    current_user.present?
  end

  def user_avatar(user, options)
    if user.avatar.attached?
      image_tag(user.avatar.variant(resize: "200x200>"), options)
    else
      fa_icon_tag("user", { class: "fa-5x fa-fw text-white" })
    end
  end
end

app/views/admin/races/_form.html.haml
= simple_form_for(@race, wrapper: :horizontal_form, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :series
    = f.input :slug
    = f.input :short_description
    = f.input :long_description
    = f.input :facebook_event_link

  .form-actions.col-md-offset-3.col-md-9
    = f.button :submit
    = f.button :cancel, to: races_path

app/views/admin/races/edit.html.haml
- @title = "Editing race"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/races/new.html.haml
- @title = "New race"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/series/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admin, @series]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :short_description
    = f.input :full_description
    = f.input :allows_mass_registration
    = f.input :mass_registration_open_at
    = f.input :contact_email
    = f.input :contact_name

  .form-actions
    = f.button :submit, class: "btn btn-outline-success btn-md pull-right"

app/views/admin/series/edit.html.haml
- @title = "Editing #{@series.name}"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/series/index.html.haml
- @title = "Series"

- content_for :description do
  %p
    Series are collections of races grouped around a central theme. They can be
    configured to support mass registration and are often marketed cohesively.


- content_for :actions do
  = link_to new_admin_series_path, class: 'btn btn-outline-primary btn-large pull-right' do
    = fa_icon_tag "plus"
    Add A Series

.row
  - @series.each do |series|
    .col-4
      .card.card-image
        .card-header
          %img.card-img-top{:alt => "It's Fill Murray everybody", :src => "http://fillmurray.com/300/210"}/
          .floor-fade
          %h4.card-title= series.name
        .card-body
          %p.card-text= series.short_description
        .card-footer.d-flex.justify-content-between
          = link_to fa_icon_tag("eye"), admin_series_path(series), rel: 'tooltip', title: 'Show'
          = link_to fa_icon_tag("pencil"), edit_admin_series_path(series), rel: 'tooltip', title: 'Edit'
          = link_to fa_icon_tag("trash"),
            admin_series_path(series),
            rel: 'tooltip',
            title: 'Delete',
            data: { confirm: 'Are you sure?' },
            method: :delete

app/views/admin/series/new.html.haml
- @title = "New Series"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/series/show.html.haml
- @title = "Showing #{@series.name}"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .form-horizontal
        .form-group
          %label.col-sm-2.form-label Name
          .uneditable-input.col-md-8.form-control
            %span= @series.name

        .form-group
          %label.col-sm-2.form-label Short description
          .uneditable-input.col-md-8.form-control
            %span= @series.short_description

        .form-group
          %label.col-sm-2.form-label Full description
          .uneditable-input.col-md-8.form-control
            %span= @series.full_description

        .form-group
          %label.col-sm-2.form-label Allows mass registration
          .uneditable-input.col-md-8.form-control
            %span= @series.allows_mass_registration

        .form-group
          %label.col-sm-2.form-label Mass registration open at
          .uneditable-input.col-md-8.form-control
            %span= @series.mass_registration_open_at

        .form-group
          %label.col-sm-2.form-label Contact email
          .uneditable-input.col-md-8.form-control
            %span= @series.contact_email

        .form-group
          %label.col-sm-2.form-label Contact name
          .uneditable-input.col-md-8.form-control
            %span= @series.contact_name

        .form-actions.col-md-offset-2
          = link_to fa_icon_tag("pencil") + ' Edit', edit_admin_series_path(@series), class: 'btn btn-primary'
          = link_to 'Back', admin_series_index_path, class: 'btn'

app/views/admin/users/destroy.html.haml
%h1 Admin::Users#destroy
%p Find me in app/views/admin/user/destroy.html.haml

app/views/admin/users/edit.html.haml
%h1 Admin::User#edit
%p Find me in app/views/admin/user/edit.html.haml

app/views/admin/users/index.html.haml
%h1 Users

app/views/admin/users/update.html.haml
%h1 Admin::User#update
%p Find me in app/views/admin/user/update.html.haml

app/views/emergency_contacts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@emergency_contact) do |f|
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :user
    = f.input :full_name
    = f.input :preferred_name
    = f.input :relation
    = f.input :cell_phone
    = f.input :last_notified

  .form-actions
    = f.button :submit

app/views/emergency_contacts/edit.html.haml
- @title = "Editing emergency_contact"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/emergency_contacts/index.html.haml
- @title = "Listing emergency_contacts"

- content_for :description do
  %p Edit this template in app/views/EmergencyContacts/index.html.haml.

- content_for :actions do
  = link_to new_emergency_contact_path, class: 'btn btn-primary btn-large pull-right' do
    = fa_icon_tag "plus"
    Add Emergency contact

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .sheet.sheet-condensed
        .sheet-inner
          %table.table
            %thead
              %tr
                %th User
                %th First name
                %th Last name
                %th Relation
                %th Cell phone
                %th Last notified
                %th
            %tbody
            - @emergency_contacts.each do |emergency_contact|
              %tr
                %td= emergency_contact.user
                %td= emergency_contact.first_name
                %td= emergency_contact.last_name
                %td= emergency_contact.relation
                %td= emergency_contact.cell_phone
                %td= emergency_contact.last_notified
                %td.actions
                  = link_to fa_icon_tag("eye-open"), emergency_contact, rel: 'tooltip', title: 'Show'
                  = link_to fa_icon_tag("pencil"), edit_emergency_contact_path(emergency_contact), rel: 'tooltip', title: 'Edit'
                  = link_to fa_icon_tag("trash"), emergency_contact, rel: 'tooltip', title: 'Delete', data: { confirm: 'Are you sure?' }, method: :delete

app/views/emergency_contacts/new.html.haml
- @title = "New emergency_contact"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/emergency_contacts/show.html.haml
- @title = "Showing emergency_contact"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .form-horizontal
        .form-group
          %label.col-sm-2.form-label User
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.user

        .form-group
          %label.col-sm-2.form-label First name
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.first_name

        .form-group
          %label.col-sm-2.form-label Last name
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.last_name

        .form-group
          %label.col-sm-2.form-label Relation
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.relation

        .form-group
          %label.col-sm-2.form-label Cell phone
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.cell_phone

        .form-group
          %label.col-sm-2.form-label Last notified
          .uneditable-input.col-md-8.form-control
            %span= @emergency_contact.last_notified

        .form-actions.col-md-offset-2
          = link_to fa_icon_tag("pencil") + ' Edit', edit_emergency_contact_path(@emergency_contact), class: 'btn btn-primary'
          = link_to 'Back', emergency_contacts_path, class: 'btn'

app/views/layouts/admin/_base.html.haml
!!! 5
= html_tag :lang => "en" do
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %meta{content: "no-cache", name: "turbolinks-cache-control"}/
    %title= [@title, app_name].compact.join(" - ")
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': 'reload'
    = yield :styles
    = favicon_link_tag
    = render 'layouts/external_js_libs'
    = yield :external_js_libs
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = yield :javascript
    = yield :head
  %body{:class => @body_class, "data-js-libs" => "bootstrap fitie metis forms sidenav prism clipboard bs-switch #{yield :js_libs}"}
    = yield

app/views/layouts/admin/_flashes.html.haml
.row
  .col-sm-12.col-md-8.mr-auto.ml-auto
    - if alert
      .alert.alert-error
        %a.close{"data-dismiss" => "alert"} ×
        = fa_icon_tag "remove"
        = alert
    - if notice
      .alert.alert-warning
        %a.close{"data-dismiss" => "alert"} ×
        = fa_icon_tag "info-sign"
        = notice

app/views/layouts/admin/_side_menu.html.haml
%nav.nav-side-menu.navbar-dark.navbar-expand-sm
  = render partial: "layouts/admin/side_menu_header"
  #menu-content.navbar-collapse.collapse
    .nav-side-container
      %ul.navbar-nav.flex-column
        = render partial: "layouts/admin/side_menu_main_content"

app/views/layouts/admin/_side_menu_header.html.haml
.navbar-header
  .profile
    = random_avatar 60, "rounded-circle profile-image"
    .profile-body
      %h6= current_user.name
      .user-links
        %a.btn.btn-link{"data-original-title" => "Profile", "data-placement" => "bottom", "data-toggle" => "tooltip", href: "#"}
          = theme_icon_tag "user"
        %a.btn.btn-link{"data-original-title" => "Messages", "data-placement" => "bottom", "data-toggle" => "tooltip", href: "#"}
          = theme_icon_tag "email"
        %a.btn.btn-link{"data-original-title" => "Settings", "data-placement" => "bottom", "data-toggle" => "tooltip", href: "#"}
          = theme_icon_tag "settings"
        %a.btn.btn-link{"data-original-title" => "Logout", "data-placement" => "bottom", "data-toggle" => "tooltip", href: "#"}
          = theme_icon_tag "power-off"
  %button.navbar-toggler.collapsed{"aria-controls" => "menu-content", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#menu-content", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon

app/views/layouts/admin/_side_menu_main_content.html.haml
%li.nav-item
  %a.nav-link.active
    Fo
%li.nav-item
  %a.nav-link{"aria-expanded" => "false", href: "#"}
    = theme_icon_tag "layout-menu-v"
    %span Multi-Level Menu
    %span.fa.arrow
  %ul.nav-item.nav-second-level.collapse{"aria-expanded" => "false"}
    %li.nav-item
      %a.nav-link{href: "#"} Second Level Item
    %li.nav-item
      %a.nav-link{href: "#"} Second Level Item
    %li.nav-item
      %a.nav-link{"aria-expanded" => "false", href: "#"}
        %span Third Level
        %span.fa.arrow
      %ul.nav-item.nav-third-level.collapse
        %li.nav-item
          %a.nav-link{href: "#"} Third Level Item
        %li.nav-item
          %a.nav-link{href: "#"} Third Level Item
        %li.nav-item
          %a.nav-link{href: "#"} Third Level Item
        %li.nav-item
          %a.nav-link{"aria-expanded" => "false", href: "#"}
            %span Fourth Level
            %span.fa.arrow
          %ul.nav-item.nav-fourth-level.collapse{"aria-expanded" => "false"}
            %li.nav-item
              %a.nav-link{href: "#"} Fourth Level Item
            %li.nav-item
              %a.nav-link{href: "#"} Fourth Level Item
            %li.nav-item
              %a.nav-link{href: "#"} Fourth Level Item
            %li.nav-item
              %a.active{href: "#"} Fourth Level Item

app/views/races/index.html.haml
- @title = "Listing races"

- content_for :description do
  %p Edit this template in app/views/Races/index.html.haml.

- content_for :actions do
  = link_to new_race_path, class: 'btn btn-primary btn-large pull-right' do
    = fa_icon_tag "plus"
    Add Race

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .sheet.sheet-condensed
        .sheet-inner
          %table.table
            %thead
              %tr
                %th Name
                %th Series
                %th Slug
                %th Short description
                %th Long description
                %th Facebook event link
                %th
            %tbody
            - @races.each do |race|
              %tr
              %td= race.name
              %td= race.series
              %td= race.slug
              %td= race.short_description
              %td= race.long_description
              %td= race.facebook_event_link
              %td.actions
                = link_to fa_icon_tag("eye-open"), race, rel: 'tooltip', title: 'Show'
                = link_to fa_icon_tag("pencil"), edit_race_path(race), rel: 'tooltip', title: 'Edit'
                = link_to fa_icon_tag("trash"), race, rel: 'tooltip', title: 'Delete', data: { confirm: 'Are you sure?' }, method: :delete

app/views/races/show.html.haml
- @title = "Showing race"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .form-horizontal
        .form-group
          %label.col-sm-2.form-label Name
          .uneditable-input.col-md-8.form-control
            %span= @race.name

        .form-group
          %label.col-sm-2.form-label Series
          .uneditable-input.col-md-8.form-control
            %span= @race.series

        .form-group
          %label.col-sm-2.form-label Slug
          .uneditable-input.col-md-8.form-control
            %span= @race.slug

        .form-group
          %label.col-sm-2.form-label Short description
          .uneditable-input.col-md-8.form-control
            %span= @race.short_description

        .form-group
          %label.col-sm-2.form-label Long description
          .uneditable-input.col-md-8.form-control
            %span= @race.long_description

        .form-group
          %label.col-sm-2.form-label Facebook event link
          .uneditable-input.col-md-8.form-control
            %span= @race.facebook_event_link

        .form-actions.col-md-offset-2
          = link_to fa_icon_tag("pencil") + ' Edit', edit_race_path(@race), class: 'btn btn-primary'
          = link_to 'Back', races_path, class: 'btn'

app/views/static_pages/_footer.html.haml
%footer.bg-dark
  .container
    .row.no-gutter.bg-dark.p-5
      .col-sm-12.col-md-2
        .d-flex.flex-column.flex-wrap.align-items-start.justify-content-center
          %img.mb-3.img-fluid{src: "#{image_path('spectrum-logo-full')}", width: "120"}
      .col-sm-12.col-md-10.ml-md-auto.text-white
        .row
          .col-sm-12.col-md-3
            %h6 NAVIGATION
            %ul.list-unstyled
              %li
                %a.text-hover-light{href: root_path} Home
              %li
                %a.text-hover-light{href: "javascript:"} About
              %li
                %a.text-hover-light{href: "javascript:"} Races
              %li
                %a.text-hover-light{href: "javascript:"} Contact
          .col-sm-12.col-md-3
            %h6 LEGAL
            %ul.list-unstyled
              %li
                %a.text-hover-light{href: terms_of_service_path} Terms of Service
              %li
                %a.text-hover-light{href: privacy_path} Privacy Policy
              %li
                %a.text-hover-light{href: "javascript:"} Cookie Policy
          .col-sm-12.col-md-3
            %h6 SUPPORT
            %ul.list-unstyled
              %li
                %a.text-hover-light{href: "javascript:"} FAQ
              %li
                %a.text-hover-light{href: "javascript:"} Help Desk
              %li
                %a.text-hover-light{href: "javascript:"} Knowledge Base
          .col-sm-12.col-md-3
            %h6 EMAIL LIST
            %form{action: ""}
              %input.form-control.text-white.text-focus-dark.small{placeholder: "Your Email", type: "text"}/
              %button.btn.btn-success.btn-sm.btn-block.mt-2{type: "button"} Get Notified
    .row.no-gutter.bg-dark.p-4
      .col-sm-12.text-center
        %p.small.text-muted.m-0 © 2018 - SPECTRUM TRAIL RUNNING

app/views/static_pages/_nav.html.haml
= render partial: 'content_blocks/landing_navs/1', locals: { nav_class: 'navbar-dark' }

app/views/static_pages/_navigation.html.haml
%nav{class: "navbar navbar-landing navbar-light navbar-expand-lg my-0"}
  %a.navbar-brand{href: root_path}
    = image_tag image_path('spectrum-logo-no-text.png'), class: 'mr-2' do
      Spectrum
  %button.navbar-toggler{"aria-controls" => "standardNavbar", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#standardNavbar", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #standardNavbar.collapse.navbar-collapse
    %ul.nav.navbar-nav.ml-auto
      %li.nav-item
        %a.nav-link{href: "javascript:"} SERIES
      %li.nav-item
        %a.nav-link{href: "javascript:"} RACES
      %li.nav-item
        %a.nav-link{href: "javascript:"} MORE
      %li.nav-item
        - if current_user?
          %a.btn.btn-sm.btn-primary{href: registrations_path} PROFILE
        - else
          %a.btn.btn-sm.btn-primary{href: new_user_session_path} SIGN IN
      %li.nav-item
        %a.btn.btn-sm.btn-success.text-white{href: new_user_registration_path} SIGN UP

app/views/static_pages/home.html.haml
= render "static_pages/home_sections/1"
= render "static_pages/home_sections/2"
%section
= render "footer"

app/views/static_pages/home_sections/_1.html.haml
= content_for :js_libs, "parallax"
%main.landing-4
  .parallax-window{"data-image-src" => "#{asset_path('landing-1.jpg')}", "data-parallax" => "scroll", "data-speed" => "0.5"}
    .container.pt-5.pb-5
      .text-white
        = render partial: "navigation"
      .row.pt-5.pb-5
        .col-sm-12.col-md-7.ml-md-auto.mr-md-auto.text-center.text-white.mt-5
          %h1.text-shadow-light.leading-normal The Best Trail Racing in Texas
          %p.lead.font-weight-medium.mt-5.text-shadow-light
            %strong Spectrum Trail Racing
            is a community of hard working, big loving trail blazers.
            Looking to make friends or test your distance or speed limits? You’re in the right place.
          %a.btn.btn-lg.btn-circle.btn-success.text-white.text-hover-dark{href: "javascript:"} Find a Race

app/views/static_pages/home_sections/_2.html.haml
%section.bg-primary
  .container
    .row.pt-5.pb-5
      .col-sm-12.col-md-4.text-center.text-white
        .bg-circle.mb-4
          = theme_icon_tag "eye", class: "text-opacity-9 display-3"
        %h4 Scenic
        %p.lead.px-5
          Sick of doing laps around small parks? So are we. Our race venues offer a true trail running experience.
      .col-sm-12.col-md-4.text-center.text-white
        .bg-circle.text-white.mb-4
          = theme_icon_tag "support", class: "display-3"
        %h4 Supported
        %p.lead.px-5
          Beyond fully stocked aid stations, we have medically trained Search & Rescue staff at each of our races.
      .col-sm-12.col-md-4.text-center.text-white
        .bg-circle.text-white.mb-4
          = theme_icon_tag "pulse", class: "display-3"
        %h4 Festive
        %p.lead.px-5
          Our post race parties will rock your socks off. Craft beer, brick oven pizza, and live music!

app/views/users/_avatar_upload.html.haml
.thumbnail
  = user_avatar(current_user, class: 'rounded-circle shadow')